---

# https://github.com/actions/starter-workflows/blob/master/ci/go.yml

name: Go

on:
    push:
    pull_request:

jobs:
    build:
        name: build
        runs-on: ubuntu-18.04
        steps:

        - name: Install Go 1.14
          uses: actions/setup-go@v2
          with:
            go-version: '^1.14'

        - name: Check out code into the Go module directory
          uses: actions/checkout@v2

        - name: build
          run: go build -v